# Generated by Django 4.1.6 on 2023-02-09 04:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tb_borrow_book',
            old_name='m_user',
            new_name='m_name',
        ),
    ]
