# Generated by Django 4.1.6 on 2023-02-09 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookapp', '0003_rename_m_name_tb_borrow_book_m_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tb_borrow_book',
            name='br_date_rt',
            field=models.DateField(null=True),
        ),
    ]
